# Generated by Django 5.1.4 on 2024-12-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Indiquez la bonne option (A, B, C ou D).', max_length=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
